# --- Change what appears in the banner --- #
title: Learn Spanish
description: For beginners

# --- Change language of site --- #
lang: en

# --- List of links in the navigation bar --- #
# --- Only change these if you change the name of your .md files!! --- #
# --- And, only change the names of the HTML files e.g. page2.html --- #
github:
  page1: Home.html
  Conversation: Conversation.html
  Verbs: Verbs.html
  Vocabulary: Vocabulary.html
  Activities: Activities.html
